@host = http://localhost:3012
@apiPath = http://localhost:3012/api/persons
@id = 6a2089df0573b04c5f0511fb

### GET ALL PEOPLE
GET {{apiPath}} 

### GET A PERSON BY ID
GET {{apiPath}}/{{id}}

### DELETE A PERSON
DELETE {{apiPath}}/{{id}}

### POST NEW PERSON
POST {{apiPath}} HTTP/1.1
Content-Type: application/json

{
    "name":"O",
    "number":"657483920"
}

### UPDATE A PERSON
PUT {{apiPath}}/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name":"Oksana",
    "number":"22222"
}

### GET INFO
GET {{host}}/info 